# Generated by Django 5.1.1 on 2024-09-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedata', '0002_alter_agent_background_alter_agent_full_portrait_and_more_squashed_0009_rename_list_horintal_icon_map_list_horizontal_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gamedata.map')),
            ],
        ),
    ]
