# Generated by Django 5.1.1 on 2024-09-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_alter_agent_uuid'),
        ('matches', '0003_alter_match_options_alter_match_uuid'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='gamedata.map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.team'),
        ),
    ]
