# Generated by Django 5.1.1 on 2024-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-31'),
            preserve_default=False,
        ),
    ]
