# Generated by Django 5.1.1 on 2024-09-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_at',
        ),
    ]
