# Generated by Django 5.1.1 on 2024-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_winner_squashed_0010_match_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
