# Generated by Django 5.1.1 on 2024-10-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
