# Generated by Django 5.1.1 on 2024-11-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0016_map_splash'),
        ('matches', '0013_remove_match_url_match_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='gamedata.map'),
        ),
    ]
