# Generated by Django 5.1.1 on 2024-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_match_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
