# Generated by Django 5.1.1 on 2025-01-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0017_alter_agent_options_alter_map_options_and_more'),
        ('matches', '0015_match_is_finished'),
        ('teams', '0004_alter_team_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is Finished'),
        ),
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='gamedata.map', verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.team', verbose_name='Winning Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube URL'),
        ),
    ]
