# Generated by Django 5.1.1 on 2024-09-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_map_alter_match_winner'),
        ('teams', '0002_alter_team_match_alter_team_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='matches.match'),
        ),
    ]
