# Generated by Django 5.1.1 on 2025-01-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_alter_match_options_alter_match_created_at_and_more'),
        ('stats', '0015_alter_stat_ace_alter_stat_agent_alter_stat_assists_and_more'),
        ('teams', '0004_alter_team_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.match', verbose_name='match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='stats.Stat', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
    ]
