# Generated by Django 5.1.1 on 2024-09-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_icon', models.ImageField(blank=True, null=True, upload_to='maps/icons/')),
                ('list_horintal_icon', models.ImageField(blank=True, null=True, upload_to='maps/icons/')),
                ('list_vertical_icon', models.ImageField(blank=True, null=True, upload_to='maps/icons/')),
                ('splash', models.ImageField(blank=True, null=True, upload_to='maps/splashes/')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='roles/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('tier', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to='tiers/icons/')),
                ('large_icon', models.ImageField(blank=True, null=True, upload_to='tiers/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='agents/icons/')),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to='agents/icons/')),
                ('full_portrait', models.ImageField(blank=True, null=True, upload_to='agents/portraits/')),
                ('background', models.ImageField(blank=True, null=True, upload_to='agents/backgrounds/')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gamedata.role')),
            ],
        ),
    ]
