# Generated by Django 5.1.1 on 2024-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='background',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_portrait',
            field=models.CharField(default='delete', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='small_icon',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
    ]
