# Generated by Django 5.1.1 on 2024-09-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_alter_agent_background_alter_agent_full_portrait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='uuid',
        ),
    ]
