# Generated by Django 5.1.1 on 2024-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_remove_tier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='display_icon',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='list_horintal_icon',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='list_vertical_icon',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='splash',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
