# Generated by Django 5.1.1 on 2024-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0004_alter_map_display_icon_alter_map_list_horintal_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='icon',
            field=models.CharField(default='Oi', max_length=255),
            preserve_default=False,
        ),
    ]
