# Generated by Django 5.1.1 on 2024-09-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0005_alter_role_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
