# Generated by Django 5.1.1 on 2024-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_alter_agent_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='icon',
        ),
    ]
