# Generated by Django 5.1.1 on 2024-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0007_remove_agent_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='icon',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
    ]
