# Generated by Django 5.1.1 on 2024-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamedata",
            "0002_alter_agent_background_alter_agent_full_portrait_and_more_squashed_0009_rename_list_horintal_icon_map_list_horizontal_icon",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="list_horizontal_icon",
            field=models.CharField(max_length=255),
        ),
    ]
