# Generated by Django 5.1.1 on 2024-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0010_alter_map_list_horizontal_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='large_icon',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tier',
            name='small_icon',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
