# Generated by Django 5.1.1 on 2024-10-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0011_alter_tier_large_icon_alter_tier_small_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='background',
            field=models.ImageField(upload_to='agents/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_portrait',
            field=models.ImageField(upload_to='agents/full_portraits/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='icon',
            field=models.ImageField(upload_to='agents/icons/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='small_icon',
            field=models.ImageField(upload_to='agents/small_icons/'),
        ),
    ]
