# Generated by Django 5.1.1 on 2024-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0012_alter_agent_background_alter_agent_full_portrait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='list_horizontal_icon',
        ),
        migrations.AlterField(
            model_name='map',
            name='display_icon',
            field=models.ImageField(upload_to='maps/display_icons/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='list_vertical_icon',
            field=models.ImageField(upload_to='maps/vertical_icons/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='splash',
            field=models.ImageField(upload_to='maps/splashes/'),
        ),
    ]
