# Generated by Django 5.1.1 on 2024-10-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0013_remove_map_list_horizontal_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='list_vertical_icon',
            new_name='vertical_icon',
        ),
        migrations.RemoveField(
            model_name='map',
            name='display_icon',
        ),
    ]
