# Generated by Django 5.1.1 on 2024-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0014_rename_list_vertical_icon_map_vertical_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='splash',
        ),
        migrations.AlterField(
            model_name='agent',
            name='background',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_portrait',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='icon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='small_icon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='vertical_icon',
            field=models.CharField(max_length=255),
        ),
    ]
