# Generated by Django 5.1.1 on 2025-01-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0016_map_splash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tier',
            options={'verbose_name': 'Tier', 'verbose_name_plural': 'Tiers'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='background',
            field=models.CharField(max_length=255, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='full_portrait',
            field=models.CharField(max_length=255, verbose_name='Full Portrait'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Agent Name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gamedata.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='small_icon',
            field=models.CharField(max_length=255, verbose_name='Small Icon'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Map Name'),
        ),
        migrations.AlterField(
            model_name='map',
            name='splash',
            field=models.CharField(max_length=255, verbose_name='Splash Art'),
        ),
        migrations.AlterField(
            model_name='map',
            name='vertical_icon',
            field=models.CharField(max_length=255, verbose_name='Vertical Icon'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='division',
            field=models.CharField(max_length=20, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='large_icon',
            field=models.CharField(max_length=255, verbose_name='Large Icon'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='small_icon',
            field=models.CharField(max_length=255, verbose_name='Small Icon'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tier'),
        ),
    ]
