# Generated by Django 5.1.1 on 2024-09-26 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('stats', '0001_initial'), ('stats', '0002_initial'), ('stats', '0003_alter_stat_agent_alter_stat_match_alter_stat_team'), ('stats', '0004_alter_stat_ace_alter_stat_agent_alter_stat_assists_and_more'), ('stats', '0005_alter_stat_match'), ('stats', '0006_remove_stat_match_alter_stat_assists_and_more'), ('stats', '0007_alter_stat_unique_together'), ('stats', '0008_alter_stat_ace_alter_stat_mvp')]

    initial = True

    dependencies = [
        ('gamedata', '0005_alter_role_icon'),
        ('gamedata', '0006_alter_agent_uuid'),
        ('gamedata', '0008_agent_icon'),
        ('matches', '0001_initial'),
        ('matches', '0004_alter_match_map_alter_match_winner'),
        ('matches', '0010_match_created_at'),
        ('teams', '0001_initial'),
        ('teams', '0002_alter_team_match_alter_team_uuid'),
        ('teams', '0003_alter_team_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('assists', models.PositiveIntegerField(blank=True, null=True)),
                ('mvp', models.BooleanField(default=False)),
                ('ace', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='gamedata.agent')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='teams.team')),
            ],
            options={
                'unique_together': {('player', 'team')},
            },
        ),
    ]
