# Generated by Django 5.1.1 on 2024-09-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_alter_agent_background_alter_agent_full_portrait_and_more_squashed_0009_rename_list_horintal_icon_map_list_horizontal_icon'),
        ('gamedata', '0002_alter_agent_background_alter_agent_full_portrait_and_more_squashed_0009_rename_list_horintal_icon_map_list_horizontal_icon'),
        ('matches', '0004_alter_match_map_alter_match_winner'),
        ('matches', '0005_alter_match_winner_squashed_0010_match_created_at'),
        ('stats', '0001_initial'),
        ('teams', '0001_initial'),
        ('teams', '0002_alter_team_match_alter_team_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='ace',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='gamedata.agent'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mvp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='matches.match'),
        ),
    ]
