# Generated by Django 5.1.1 on 2024-09-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_alter_agent_uuid'),
        ('matches', '0004_alter_match_map_alter_match_winner'),
        ('stats', '0002_initial'),
        ('teams', '0002_alter_team_match_alter_team_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='gamedata.agent'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='teams.team'),
        ),
    ]
