# Generated by Django 5.1.1 on 2024-09-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_agent_icon'),
        ('stats', '0003_alter_stat_agent_alter_stat_match_alter_stat_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ace',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='gamedata.agent'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mvp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
