# Generated by Django 5.1.1 on 2024-09-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_created_at'),
        ('stats', '0004_alter_stat_ace_alter_stat_agent_alter_stat_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='matches.match'),
        ),
    ]
