# Generated by Django 5.1.1 on 2024-09-22 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_remove_stat_match_alter_stat_assists_and_more'),
        ('teams', '0003_alter_team_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('player', 'team')},
        ),
    ]
