# Generated by Django 5.1.1 on 2024-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_stat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mvp',
            field=models.BooleanField(default=False),
        ),
    ]
