# Generated by Django 5.1.1 on 2024-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_stat_ace_alter_stat_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ace',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mvp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
