# Generated by Django 5.1.1 on 2024-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0006_remove_stat_match_alter_stat_assists_and_more_squashed_0009_alter_stat_ace_alter_stat_mvp",
        ),
        ("teams", "0003_alter_team_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="teams.team",
            ),
        ),
    ]
