# Generated by Django 5.1.1 on 2024-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_stat_first_bloods_stat_plants_stat_spikes_defused'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='average_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
