# Generated by Django 5.1.1 on 2024-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_stat_average_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
