# Generated by Django 5.1.1 on 2024-10-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_stat_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='url',
        ),
    ]
