# Generated by Django 5.1.1 on 2025-01-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0017_alter_agent_options_alter_map_options_and_more'),
        ('stats', '0014_remove_stat_url'),
        ('teams', '0004_alter_team_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ace',
            field=models.BooleanField(default=False, null=True, verbose_name='ace'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='gamedata.agent', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='assists'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='average_points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='average points'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='deaths',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='deaths'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='first_bloods',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='first bloods'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='kills',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kills'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mvp',
            field=models.BooleanField(default=False, null=True, verbose_name='mvp'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='plants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='plants'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='spikes_defused',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='spikes defused'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='teams.team', verbose_name='team'),
        ),
    ]
