# Generated by Django 5.1.1 on 2024-09-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
        ('players', '0002_alter_player_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gamedata.tier'),
        ),
    ]
