# Generated by Django 5.1.1 on 2024-09-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_uuid_alter_player_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
    ]
