# Generated by Django 5.1.1 on 2024-09-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_agent_icon'),
        ('players', '0006_remove_player_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='gamedata.tier'),
        ),
    ]
