# Generated by Django 5.1.1 on 2024-10-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0010_alter_map_list_horizontal_icon'),
        ('players', '0007_alter_player_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='main_agent',
            field=models.ForeignKey(default=22, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedata.agent'),
        ),
    ]
