# Generated by Django 5.1.1 on 2024-10-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedata", "0010_alter_map_list_horizontal_icon"),
        ("players", "0008_player_main_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="main_agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gamedata.agent",
            ),
        ),
    ]
