# Generated by Django 5.1.1 on 2024-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_main_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_position',
            field=models.IntegerField(default=0),
        ),
    ]
