# Generated by Django 5.1.1 on 2024-10-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_last_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_position',
            new_name='last_position_change',
        ),
    ]
