# Generated by Django 5.1.1 on 2024-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_rename_last_position_player_last_position_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_position',
            field=models.IntegerField(default=0),
        ),
    ]
