# Generated by Django 5.1.1 on 2024-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0013_rankinglog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="last_position",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_position_change",
        ),
        migrations.AlterField(
            model_name="rankinglog",
            name="last_position",
            field=models.IntegerField(
                default=0, help_text="Last position in the ranking"
            ),
        ),
        migrations.AlterField(
            model_name="rankinglog",
            name="last_position_change",
            field=models.IntegerField(
                default=0,
                help_text="Show if the player went up or down in the ranking since the last update",
            ),
        ),
    ]
