# Generated by Django 5.1.1 on 2024-10-21 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_remove_player_last_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and spaces', regex='^[\\w ]+$')]),
        ),
    ]
