# Generated by Django 5.1.1 on 2024-11-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_alter_player_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
