# Generated by Django 5.1.1 on 2024-11-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_player_is_approved_alter_player_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='include_in_draft',
            field=models.BooleanField(default=True, help_text='Indicates if the player is wants to be included in the draft'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the player is approved to play in matches'),
        ),
    ]
