# Generated by Django 5.1.1 on 2025-01-05 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0017_alter_agent_options_alter_map_options_and_more'),
        ('players', '0019_player_include_in_draft_alter_player_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='will_play_the_next_match',
            field=models.BooleanField(default=False, help_text='Indicates if the player will play the next match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='gamedata.tier', verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and spaces', regex='^[\\w ]+$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='rankinglog',
            name='last_position',
            field=models.IntegerField(default=0, help_text='Last position in the ranking', verbose_name='Last Position'),
        ),
        migrations.AlterField(
            model_name='rankinglog',
            name='last_position_change',
            field=models.IntegerField(default=0, help_text='Show if the player went up or down in the ranking since the last update', verbose_name='Last Position Change'),
        ),
        migrations.AlterField(
            model_name='rankinglog',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
    ]
